### ISSUE TITLE
Extension not available on packagist.org

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-pageimage#23]
I just noticed that this extension is not available on Packagist and thus not installable via Contao's Composer client.

**Comment by aschempp** [comment]
You can always install it from `contao-legacy`…

**Comment by qzminski** [comment]
Still should be in your terminal42 account :wink:

**Comment by fritzmg** [comment]
> You can always install it from contao-legacy…

Of course, and since the versions are the same, it wouldn't matter anyway. But still, all or most of the other terminal42 extensions are available on packagist as well.

I'll change the title of the issue accordingly.

**Comment by amenk** [comment]
+1

**Comment by amenk** [comment]
If you install from legacy there is no GIT support. Which would be helpful if somebody want's to make a PR!

**Comment by aschempp** [comment]
https://packagist.org/packages/terminal42/contao-pageimage
