### ISSUE TITLE
Mehrfachauswahl im File-Picker gewollt?

### ISSUE THREAD

**Issue by Hendriks** [terminal42/contao-pageimage#25]
Es führt bei unerfahrenen Redakteuren schnell zu Fehlern, dass hier mehrere Bilder ausgewählt werden können... Sollte hier nicht besser die Einfach-Auswahl aktiviert werden?

**Comment by aschempp** [comment]
Die Mehrfachauswahl wird in der aktuellen Version benötigt, denn man kann im Frontend-Modul dann auch mehrere ausgeben. Entweder z.B. als Slider, oder jeweils das erste Bild woanders als das zweite Bild.

**Comment by Hendriks** [comment]
Ah, ok... Sorry, habe auch gerade den Feature-Request gesehen... Trotzdem für Redakteure (wenn es nur um ein Bild gehen soll) schnell etwas verwirren; bzw. dann muss man immer darauf achten, dass die alte Auswahl vor einer Neuauswahl zunächst gelöscht wird, bzw. die Reihenfolge stimmt... Na ja, man kann es nicht allen Recht machen.. ;)

**Comment by aschempp** [comment]
Genau. Es stört mich auch (etwas), vielleicht finden wir für eine nächste Version eine bessere Lösung.

**Comment by Hendriks** [comment]
Oder zumindest einfach mal den Hilfetext unter dem Auswahlmodul dahingehend anpasssen, z.B.: "...das erste Bild in der Reihenfolge wird als Hauptmotiv verwendet...", o.ä.

**Comment by Hendriks** [comment]
Wo finde ich denn die "weiteren" Bild-Links in den Template-Variablen..!?!
