### ISSUE TITLE
"Filemount"-Ausschnitt im Dateiwähler nicht veränderbar

### ISSUE THREAD

**Issue by Hendriks** [terminal42/contao-pageimage#26]
Hallo nochmals Andreas,

wo ich das Modul für einen Kunden gerade noch fertig eingerichtet habe, fällt mir auf, dass es anscheinend ein Problem mit dem Dateiwähler gibt:

Im Dateiwähler kann man ja normalerweise (genauso wie in der Dateiverwaltung) den sichtbaren Ausschnitt ("Filemount") des Ordner-Baumes verändern; indem man auf einen Ordnernamen klickt, bzw. über die "Breadcrumbs" im gelben Feld oben diesen dann auch wieder zurück-erweitert...

Dabei fiel mir jetzt folgendes Phänomen/Problem auf:

Zunächst hatte ich (egal ob als Admin oder "Redakteur") keine Möglichkeit den (zu diesem Zeitpunkt) eingeloggten Ausschnitt im Pageimage-Dateiwähler wieder auf die Mutterknoten zu erweiteren. Im Dateiwähler eines Content-Elements aus einem Artikel sah ich, dass dort der selbe Ausschnitt aktiviert war. Dort konnte ich allerdings die Übersicht wieder komplett (bis in den Datei-Root) öffnen. Beim Zurückkehren in einen Pageimage-Dateiwähler war die Übersicht dann auch wieder komplett geöffnet. Irgendwie scheinen die beiden Module da also gekoppelt zu sein. Jedoch kann ich im Pageimage-Dateiwähler den sichtbaren Ausschnitt nach wie vor nicht verändern; bei Klick auf einen Ordnernamen passiert also nichts...

Ne Idee was das sein könnte? Kann ich meinem Kunden so natürlich nicht abliefern...

Viele Grüße, Hendriks

**Comment by Toflar** [comment]
Der Dateiwähler ist doch vom Contao Core und hat nichts mit pageimage zu tun?

**Comment by Hendriks** [comment]
Mag sein, dennoch nicht wünschenswert so... ;/

**Comment by Hendriks** [comment]
In seinen anderen "Instanzen" funktioniert der / das ja auch wie es soll; also egal ob bei den Content-Elements, den Artikel- oder den News-Teasern... Da sollte das doch für Drittmodule auch entsprechend funktionieren...!?

**Comment by Toflar** [comment]
Also wie gesagt, am Dateiwähler können wir nichts machen. Aber noch wenn du den wichtigen Teil da auswählen könntest, so würde er von pageimage im Frontend dann eh nicht unterstützt. Dafür gibt es ja schon ein Ticket: https://github.com/terminal42/contao-pageimage/issues/21
