### ISSUE TITLE
SVGs auswählen

### ISSUE THREAD

**Issue by manjarco** [terminal42/contao-pageimage#27]
Hi,
kann man es irgendwie möglich machen auch SVGs als pageimage auszuwählen? Mit einer einfachen Anpassung per dcaconfig á la:

$GLOBALS['TL_DCA']['tl_page']['fields']['pageImage'] = array
(
    'label'         => &$GLOBALS['TL_LANG']['tl_page']['pageImage'],
    'inputType'     => 'fileTree',
    'exclude'       => true,
    'eval'          => array('fieldType'=>'checkbox', 'orderField'=>'pageImageOrder', 'multiple'=>true, 'files'=>true, 'filesOnly'=>true, 'extensions'=>'jpg,jpeg,gif,png,svg', 'isGallery'=>true),
    'sql'           => "blob NULL",
);

kann ich zwar eine svg auswählen, sie kommt aber nicht im FE an.

**Comment by Toflar** [comment]
Mit welcher Contao-Version? Das müsste eigentlich dann gehen, wenn das da erlaubt wird. Oder was heisst "kommt nicht im FE an"?

**Comment by manjarco** [comment]
Contao 3.5.6
Im FE wird in der Variable [src] nur das Bild der übergeordneten Seite ausgegeben, das auf der Kind-Seite ausgewählte svg kommt dort nicht an. Wenn ich "Übergeordnete Bilder verwenden" in den Moduleinstellungen deaktiviere erfolgt gar keine Ausgabe.

**Comment by Toflar** [comment]
Introduced in 7b32302b44e3db2d16f82e8ea17661635b0f8d81.
