### ISSUE TITLE
fallback for alt-attribute

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-pageimage#39]
In page structure you can enter an alt-text for the page image. We maintain the alt-text in the file system, but the extension don't fall back to the information in file system. When I don't enter an alt-text in page structure, no alt-text will be served.

Could you make a fallback using the alt-text from file system if the field for alt-text in page structure is empty?

**Comment by aschempp** [comment]
Pretty sure that would be possible, but then we should have a checkbox and migration script like the Contao core had for the content elements (Metadaten überschreiben). Wanna provide a pull request?

**Comment by aschempp** [comment]
Implemented in de6bd0565949870f3552bced0f626c78734a0cf5
