### ISSUE TITLE
Bildgrössen bei Background-Darstellung

### ISSUE THREAD

**Issue by DanEi75** [terminal42/contao-pageimage#40]
Hallo

So wie es scheint, werden definitierte Bildgrössen nicht berücksichtigt, wenn die Darstellung als Background-Image gewählt wird. Bei der Einbindung als normales Bild hingegen schon. Ist das nicht möglich oder hat man es vergessen (kein Vorwurf :-)), dies dort auch zu berücksichtigen?

Thx

**Comment by aschempp** [comment]
das wird nicht möglich sein, dazu müsstest du selber CSS schreiben.

**Comment by DanEi75** [comment]
Hallo Andreas

Danke dir für die Rückmeldung. Habe es jetzt im Template 'mod_background_image' mal so ergänzt und es funktioniert. Denke, für meine Zwecke passt das.

```
<style>
html {
  background: url("<?php echo specialchars($this->src); ?>") no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
<?php 
if($this->picture['sources']):
  foreach($this->picture['sources'] as $value):
?>
@media screen and <?= $value['media'] ?> {
  html {
    background-image: url("<?= $value['src'] ?>");
  }
}
<?php
  endforeach;
endif;
?>
</style>
```

**Comment by aschempp** [comment]
Danke für die Rückmeldung. Ich dachte nicht dass das so einfach ist, so können wir das bestimmt gut übernehmen 🙃

**Comment by DanEi75** [comment]
Coole Sache! Aber bitte noch mal kritisch reviewen ;-). Ich bin so ein Quick-and-Dirty-Coder!

**Comment by aschempp** [comment]
Mach ich, aber lass doch das Ticket offen damit es nicht vergessen geht 😂

**Comment by DanEi75** [comment]
Oh 😁! Sorry. Reflex!

**Comment by albirs** [comment]
https://github.com/terminal42/contao-pageimage/blob/main/contao/templates/mod_pageimage_background.html5 funktioniert bei mir nicht in in dieser Version, es werden keine Bildgrößen ausgegeben. 
Nur mit angepassten Code aus https://github.com/terminal42/contao-pageimage/issues/40#issuecomment-503944785 (weiter oben) funktioniert es:


`
<?php ob_start() ?>
<style>
    html {
        background-image: url("<?= \Contao\StringUtil::specialchars($this->src) ?>");
        background-repeat: no-repeat;
        background-position: center;
        background-attachment: fixed;
        background-size: cover;
    }
    <?php foreach ($this->picture['sources'] as $mediaQuery): ?>
    @media <?= $mediaQuery['media'] ?> {
        html {
            background-image: url("<?= \Contao\StringUtil::specialchars($mediaQuery['src']) ?>");
        }
    }
    <?php endforeach ?>
</style>
<?php $GLOBALS['TL_HEAD'][] = ob_get_clean() ?>

`
