### ISSUE TITLE
Individuelles Template nicht auswählbar

### ISSUE THREAD

**Issue by sebssch** [terminal42/contao-pageimage#41]
<img width="593" alt="Themes › Hanika › Frontend-Module › Modul ID 33 bearbeiten - Contao Open Source CMS 2019-09-26 10-21-47" src="https://user-images.githubusercontent.com/18069290/65671412-79aa1400-e047-11e9-81e9-6cb3f9da6a1f.png">

Es sind zwei Templates angelegt. `mod_pageimage.html5` und `mod_pageimage_home.htm5`. 
Jedoch ist es nicht möglich eines der Templates dem Modul zuzuweisen. 
Contao 4.4.43

**Comment by aschempp** [comment]
Es müsste funktionieren wenn du das Template `mod_pageImage_home.html5` nennst.

**Comment by sebssch** [comment]
true - vielen Dank
