### ISSUE TITLE
img class wird nicht ausgegeben 

### ISSUE THREAD

**Issue by herrweiss77** [terminal42/contao-pageimage#47]
Wenn im Modul eine definierte Bildgröße ausgewählt wird, bei der eine CSS-Klassen für den img-Tag angegeben wurde, wird die Klasse nicht mit ausgegeben. Auch in den Template-Variablen ist die Klasse im img Array nicht vorhanden.

**Comment by aschempp** [comment]
Sollte mit 1e4c6543618ae2c4bf085f7d425454c4440b3353 behoben sein
