### ISSUE TITLE
Nach Update auf Version 4.1.0 keine Bilder mehr im Frontend

### ISSUE THREAD

**Issue by contaoacademy** [terminal42/contao-pageimage#48]
Nach dem Update von Version 4.0.1 auf 4.1.0 sind bei mir alle Bilder im Frontend verschwunden.

Erst nachdem die Option: "Generiert alle Bilder der aktuellen Seite." aktiviert wird, erscheinen die Bilder wieder.
Ist das so beabsichtigt?

![screen-20210623_fDo5udvX](https://user-images.githubusercontent.com/23719181/123093760-5682e300-d42c-11eb-9178-7c55a4cb492f.jpg)

**Comment by aschempp** [comment]
should be fixed by c0d88d3d533f2c0777d8f835fc828297162221d7
