### ISSUE TITLE
img title wird nicht ausgegeben

### ISSUE THREAD

**Issue by eiswurm** [terminal42/contao-pageimage#51]
Der Bildttitel aus der Dateiverwaltung fehlt im Template. Hier scheint es nur linkTitle zu geben. Wie bekomme ich den title in:

`<?php $this->insert('picture_default', $image['picture']); ?>`

ausgegeben?

**Comment by aschempp** [comment]
fixed in a98053b30b62ba09cecd22e92f7d32f49f0b7909
