### ISSUE TITLE
Datenbank-Änderungen können nicht ausgeführt werden

### ISSUE THREAD

**Issue by FrischBlau** [terminal42/contao-pageimage#53]
Nach einem Update auf 4.13 und PHP 8.1 können die Datenbank-Änderungen nicht ausgeführt werden. 

Bei Klick auf "Ausführen" erscheint immer wieder der gleiche Screen:

Datenbank-Migrationen
Runonce file: system/modules/pageimage/config/runonce.php

![screenshot](https://user-images.githubusercontent.com/6159447/217182735-5b7aff7f-9eab-4ec2-9c3e-995a6cbc5609.png)

**Comment by aschempp** [comment]
diese Erweiterung liefert keine `runonce.php` mit, inwiefern hat das Problem etwas mit _contao-pageimage_ zu tun?
