### ISSUE TITLE
Contao 5.1.x

### ISSUE THREAD

**Issue by sdahlmann** [terminal42/contao-pageimage#54]
Frage: Wird es für die Contao-Erweiterung "Pageimage" in Absehbarer Zeit einen Fix für Contao 5.1.x geben? Ich würde mich sehr darüber freuen.
---
Question: Will there be a fix for Contao 5.1.x for the Contao extension "Pageimage" in the above future? I would be very happy about it.

**Comment by sdahlmann** [comment]
When I create a Contao module "pageimage" under Contao 5.1.x and click on "Speichern und Schließen", I get the following error message "Internal Server Error - Was ist das Problem? - Tried to list template options for the modern fragment type "frontend_module/pageimage" but could not find any template. In case you wanted to use the legacy type "mod_pageimage", define it explicitly in the "template" property of your controller's service tag/attribute.". The installation of the DEV version worked properly via the Contao Manager.
When I create a Contao module "pageimage" under Contao 5.1.x and click on "Save and close", I get the following error message "x". The installation of the DEV version worked properly via the Contao Manager.

The module is then created and works when integrated into the "Seitenlayout".

**Comment by sdahlmann** [comment]
When I create a Contao module "pageimage" under Contao 5.1.x and click on "Speichern und Schließen", I get the following error message "Internal Server Error - Was ist das Problem? - Tried to list template options for the modern fragment type "frontend_module/pageimage" but could not find any template. In case you wanted to use the legacy type "mod_pageimage", define it explicitly in the "template" property of your controller's service tag/attribute.".

The installation of the "dev-main" version worked properly via the Contao Manager.

The module is then created and works when integrated into the "Seitenlayout".

**Comment by aschempp** [comment]
@m-vo that sounds like a Contao bug to me, wdyt?

**Comment by m-vo** [comment]
@sdahlmann Do you have the most recent version of the 5.1 branch installed?

**Comment by aschempp** [comment]
should be fixed in dde3dc6a799b7969e898b4eccffef4e3dd61a551
